In [ ]:
#Question1: Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
import numpy as np
p=np.random.randint(0,100,size=(3,3))
print(p)
q=p.T
print(q)


[[67 26 83]
 [28  0 53]
 [65 25 47]]
[[67 28 65]
 [26  0 25]
 [83 53 47]]


In [ ]:
#question2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np
arr=np.arange(10)
print("the original array is \n ",arr)
arr1=arr.reshape(2,5)
print(arr1)
arr2=arr.reshape(5,2)
print(arr2)





the original array is 
  [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# Question 3:Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np
import random
arr=np.random.rand(4,4)
print("the original array is ",arr)
arr1=np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr1)







the original array is  [[0.95908749 0.15540538 0.48334088 0.32946365]
 [0.65260307 0.04257556 0.15221501 0.78381545]
 [0.0107155  0.9014601  0.32082532 0.18077588]
 [0.4389895  0.84666354 0.62158    0.49694972]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.95908749 0.15540538 0.48334088 0.32946365 0.        ]
 [0.         0.65260307 0.04257556 0.15221501 0.78381545 0.        ]
 [0.         0.0107155  0.9014601  0.32082532 0.18077588 0.        ]
 [0.         0.4389895  0.84666354 0.62158    0.49694972 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
# question 4:Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np
arr=np.arange(10,61,5)
print(arr)




[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
#Question 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.
import numpy as np
arr=np.array(["python","numpy","pandas"])
arr_upper=np.char.upper(arr)
arr_lower=np.char.lower(arr)
arr_title=np.char.title(arr)
print(arr_upper,arr_lower,arr_title)


['PYTHON' 'NUMPY' 'PANDAS'] ['python' 'numpy' 'pandas'] ['Python' 'Numpy' 'Pandas']


In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array
import numpy as np
arr=np.array(["mitlesh","chauhan","data","science"])
arr1=np.char.join('  ',arr)
print(arr1)


['m  i  t  l  e  s  h' 'c  h  a  u  h  a  n' 'd  a  t  a'
 's  c  i  e  n  c  e']


In [ ]:
#Question 7. Create two 2D NumPy arrays and
# perform element-wise addition, subtraction, multiplication, and division.
arr1=np.array([[1,2,3],[21,22,23]])
arr2=np.array([[13,14,15],[10,11,12]])
print("the addition of the two array element wise\n",arr1+arr2)
print("the subtraction of the given array are\n ",arr2-arr1)
print("the multiplication of two array element wise \n",arr1*arr2)


the addition of the two array element wise
 [[14 16 18]
 [31 33 35]]
the subtraction of the given array are
  [[ 12  12  12]
 [-11 -11 -11]]
the multiplication of two array element wise 
 [[ 13  28  45]
 [210 242 276]]


In [ ]:
#Question 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np
id_mat=np.eye(5)
print("the identity matrix is \n",id_mat)
dig=np.diag(id_mat)
print("The diagonal is \n",dig)


the identity matrix is 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
The diagonal is 
 [1. 1. 1. 1. 1.]


In [ ]:
#question 9: Generate a NumPy array of 100 random integers between 0 and 1000.
 #Find and display all prime numbers in this array.

def prime(num):
    if num <= 1:
        return False
    for i in range(2, num):
        if num % i == 0:
            return False
    return True
import numpy as np
import random
arr=np.random.randint(1,1000,size=100)
print(arr)
prime_numbers=[num for num in arr if prime(num)]
print(" the prime numbers are\n",prime_numbers)







[900 165 875 980 110 899 910 260 187 452 489 586 786 346 579 748  37  66
 115 604 493 627   2 887 331 226 772 300 972 982 162 436 879 189 888 479
 808 380  94 709 641   5 846 873 943 574 603 470  54 803 261 294 350 250
 542 616 146 342 521 290 405 298 686 217 950 592 358 876 945 375 687 620
 671 845  60 202 850  28 368 740  87 783 212 419 563 623 963 193 772 698
 417 264 564  89 746 353 504 515  92 585]
 the prime numbers are
 [37, 2, 887, 331, 479, 709, 641, 5, 521, 419, 563, 193, 89, 353]


In [ ]:
# Create a NumPy array representing daily temperatures for a month.
# Calculate and display the weekly averages.
import numpy as np
#here I assumed the temparature will be in range of 20 to 35 degree celcius
arr=np.random.uniform(20,35,30)
print("the array of temparatures is \n",arr)
arr1=arr[:28].reshape(4,7)
arr2=arr[28:]
weekly_avg=arr1.mean(axis=1)

print("the weekly average temparature is in the below arry",weekly_avg)
if arr2.size >0:
  rem_avg=arr2.mean()
  print(f"the avrage of the {arr2.size} days is \n",rem_avg)





the array of temparatures is 
 [28.80815472 32.39566453 29.91815095 32.21163496 24.87848685 22.76769489
 20.9145875  28.22528135 24.42713376 32.79648712 34.12935939 24.19004113
 28.70604021 26.49539281 21.73741589 33.94355425 30.44873431 29.91834327
 31.31830286 26.18470686 25.70130506 21.72332917 28.04997411 22.00713978
 29.18882195 22.49727193 20.08072572 25.8672998  31.38733591 34.89395294]
the weekly average temparature is in the below arry [27.41348206 28.42424797 28.46462322 24.20208035]
the avrage of the 2 days is 
 33.14064442436357
