**Question1.** Explain the purpose and advantages of NumPy in scientific computing and data analysis.
 How does it enhance Python's capabilities for numerical operations?
 **Answer:**
NumPy, short for Numerical Python, is a powerful library that significantly boosts Python's capabilities for scientific computing and data analysis.

Purpose and Advantages of NumPy:
Efficient Array Computations:

 NumPy provides support for large, multi-dimensional arrays and matrices which allows for efficient array computations, which are crucial for numerical operations and data manipulation.
 Since it is implemeted in c it makes it faster
Broadcasting:
 This allows operations to be performed on arrays of different shapes which Makes array operations more intuitive and less verbose, enhancing productivity.

Extensive Functionality:
 NumPy offers a wide range of mathematical and statistical functionsso that Users can perform complex calculations and analyses without needing additional libraries.

Integration with Other Libraries:
 NumPy serves as the foundation for many other scientific computing libraries (e.g., SciPy, Pandas, Matplotlib).
which  Seamlessly integrates with these libraries, providing a robust ecosystem for scientific computing.

Ease of Use:
 It has a user-friendly syntax that closely resembles mathematical notation.
So this Lowers the learning curve and makes it accessible to both beginners and experienced users.


**Question 2**. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?
**Answer**:The basic differnce between the np.mean() and np.avrage()
is that np.mean() simply calculate the average of the data but np.average() also takes into account the weight of the factors that are of unequal importance .
we should use np.mean when there is eqaul amount of importance is given to all the constraints and np.average is used when differnt factor have diffrence importance.


**Question 3:**3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.
**Answer**:There are mainly two way to reverse the array first we will se one dimentional array
here we use the index method to revese the array like list
other way is to use np.flip() the examples elaborating the method is below


In [ ]:
#example for one dimention
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr1=arr[::-1]
print(f" the reverse of the array{arr} is \n",arr1)
arr2=np.flip(arr)
print(f"the flip method also works fine to reverse the array{arr} as below \n",arr2)


 the reverse of the array[1 2 3 4 5 6] is 
 [6 5 4 3 2 1]
the flip method also works fine to reverse the array[1 2 3 4 5 6] as below 
 [6 5 4 3 2 1]


In [ ]:
#for two dimestional array
import numpy as np
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ar1=ar[::-1, ]
print(f"the reverse for \n{ar}\n along axis 0 is\n",ar1)
#using slicing
ar2=np.flip(ar,axis=0)
print("the reverse of the given array along axis 0 using flip is below\n",ar2)
ar3=np.flip(ar,axis=1)
print("the reverse of the given array along axis 1 using flip is below\n",ar3)
ar4=np.flip(ar)
print("the reverse of the given array along both axis using flip is below\n",ar4)


the reverse for 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 along axis 0 is
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
the reverse of the given array along axis 0 using flip is below
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
the reverse of the given array along axis 1 using flip is below
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
the reverse of the given array along both axis using flip is below
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


**question4**. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.
**Answer:**
we can determine the data type of elements in a NumPy array using the dtype attribute.
There is important rolr of the data type in the numpy because the diffrent  data types have diffrent memory usage to store them
for example the 32 bit int take less space than 64 bit int or float  which is important when we are operating on big data set.
Sometimes the precison and accuracy is also depends on the data type


**Question 5**: Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
**Answer:**
Nd array are n dimentional array consist of the homogenous data types it is in the form of grid of values.it is versetile and very usful in the scientific calcualtions.
diffrence between the array and list in genral
1.list can have the data of diffrent types which can lead to some inconsistency whareas the array have the same data type then it is consistent .
2.ndarrays Uses less memory due to efficient storage but Lists are more memory overhead due to the dynamic nature of lists.
3. nd array are faster as they are coded in c than the convntional list
4. ndarrays are multidimentional in nature but the list in genral not .for making the list work as multi dimensionally we have to use the nested list which is a lot more complex in nature


**Question 6**. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
**Answer**:
As discussed in the previus question we saw that since the numpy library is written in the c language it is faster than the data types wrtten in the python  so the mathematical operations are also became fast because of a lost of the atrributes used in it whwre as the have not such attributes moreover the multidimensionality makes the numpy more effficient .


**Question 7**Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.
**Answer:** In summary, vstack() and hstack() are powerful functions for combining arrays in NumPy, with vstack() stacking them vertically and hstack() stacking them horizontally.
the example are below

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
ab=np.vstack((a,b))
print(ab)   #here ab is the array where array a and array are combined verstically to form an array ab
ab_h=np.hstack((a,b))
print("the horizontal merger of a and b is \n",ab_h)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
the horizontal merger of a and b is 
 [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# vstack and hstack can also be used for 2 dimension also
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[7,8,9],[10,11,12]])
arr2=np.vstack((arr,arr1))
arr3=np.hstack((arr,arr1))
print(arr2)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**Question 8:**Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.
**Answer**:
    fliplr() is used to flip the array left to right it works for the two dimesion not for one dimentional array .if we use it for one dimentional array it will throw an error
    where as the flipud() flip the array from top to bottom
    but the main difference from fliplr() is that it work fine with the one dimentional aaray too.


**Question 9**:9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
**Answer**: The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is particularly useful when you need to divide an array into equal or approximately equal parts, even if the number of elements isn't perfectly divisible.
the example is given below

In [ ]:
# here array_split() split the original array in subarray with possible equal length even if the length
# is not divisible by any sub length
import numpy as np
arr=np.arange(13)
print(arr)
arr1=np.array_split(arr,4)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


**Question 10**:  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?
**Answer**:**Vectorization** involves performing operations on entire arrays or large chunks of data without the need for explicit loops. It leverages low-level optimizations, usually written in C, to handle these operations quickly.
it is fast and also very much simple than the loops so, it add efficiency and simplicity in the code.
exaple will be given below

**Broadcasting** enables NumPy to handle operations on arrays of different shapes and sizes, as long as they are compatible. It stretches the smaller array to match the shape of the larger one without actually copying data.
it is used when the shape of the array are differnt
eg are below

In [ ]:
#vectorisation
import numpy as np
a=np.array([1,2,3,])
b=np.array([4,5,6])
c=a+b #it is vectorise addition
print(c)

[5 7 9]


In [ ]:
#brodcasting
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Broadcasting b to match the shape of a
c = a + b
print(c)


[[11 22 33]
 [14 25 36]]


In [ ]:
# using both in the code
# Matrix multiplication using vectorization and broadcasting
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

product = np.dot(a, b)
print(product)


[[19 22]
 [43 50]]
